name=OpenWeather
main=de.solarreader.plugins.openweather.OpenWeather
plugin.version=${project.version}
core.version=${solarreader.version}
build=${software.build.date}
author=Stefan Toengi
repository=https://github.com/solarreader-plugins/plugin-openweather
icon=openweather.svg
supports=OpenWeather V2.5
interfaces=URL
protocol=HTTP
